// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0U_eoYPRuS9I3hiAWMHWPjJI0sssbPRA',
    appId: '1:908629088749:android:3dd282f34dc80bdf9a2fe4',
    messagingSenderId: '908629088749',
    projectId: 'com-example-sparklearn',
    storageBucket: 'com-example-sparklearn.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNgZtbZ9E4GvXmc-5Z7uCvtb0jpc1SMnk',
    appId: '1:908629088749:web:15498d02773ac1089a2fe4',
    messagingSenderId: '908629088749',
    projectId: 'com-example-sparklearn',
    authDomain: 'com-example-sparklearn.firebaseapp.com',
    storageBucket: 'com-example-sparklearn.firebasestorage.app',
    measurementId: 'G-PPW62TZDS1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTciy9ARguzmfYQMJT18Qkv7NBn8Hs23c',
    appId: '1:908629088749:ios:b8c8bdf2920b90d79a2fe4',
    messagingSenderId: '908629088749',
    projectId: 'com-example-sparklearn',
    storageBucket: 'com-example-sparklearn.firebasestorage.app',
    iosBundleId: 'com.example.sparklearn',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTciy9ARguzmfYQMJT18Qkv7NBn8Hs23c',
    appId: '1:908629088749:ios:b8c8bdf2920b90d79a2fe4',
    messagingSenderId: '908629088749',
    projectId: 'com-example-sparklearn',
    storageBucket: 'com-example-sparklearn.firebasestorage.app',
    iosBundleId: 'com.example.sparklearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNgZtbZ9E4GvXmc-5Z7uCvtb0jpc1SMnk',
    appId: '1:908629088749:web:fe3e4164094f84909a2fe4',
    messagingSenderId: '908629088749',
    projectId: 'com-example-sparklearn',
    authDomain: 'com-example-sparklearn.firebaseapp.com',
    storageBucket: 'com-example-sparklearn.firebasestorage.app',
    measurementId: 'G-KH3FV01L1L',
  );
}
